### ISSUE TITLE
Exception in IE

### ISSUE THREAD

**Issue by floreseken** [EisenbergEffect/aspnetcore-aurelia-build-2017#2]
I get an exception opening this in IE11

JavaScript runtime error: 'Promise' is undefined

Works fine in Chrome.

Is that to be expected?

**Comment by B3zo0** [comment]
IE 11 does not support Promise so you have to use a polyfill for that. You can take a look at how they used bluebird at https://github.com/aurelia/skeleton-navigation

**Comment by MeirionHughes** [comment]
See https://github.com/jods4/aurelia-webpack-build/wiki/Promise-is-undefined

**Comment by floreseken** [comment]
Okay. Thanks for that.
