### ISSUE TITLE
HotModuleReplacement does not work, Browser dont refresh after changing

### ISSUE THREAD

**Issue by HamedFathi** [EisenbergEffect/aspnetcore-aurelia-build-2017#3]
Hi

I got your source and used these command for preparing

npm install
dotnet restore
dotnet run

but when I ran the project on localhost:5000 and changed something for example

counter.html to  <h 1> Counter NEW</ h 1>
or
counter.ts to public currentCount = 10;

the browser dont refresh 

Can anyone guide me how to fix this ? for changing in any files such as html,css,ts,js the browser refresh and HotModuleReplacement works correctly.

**Comment by zsmorris** [comment]
I ran into the exact same problem after following the same steps.  Any thoughts?  Is there a step-by-step, up-to-date "using Aurelia with Visual Studio 2017" guide anywhere maybe?  Thanks.

**Comment by TonyLugg** [comment]
Make sure you select your project in the dropdown when you F5-Debug.  The default seems to be IIS Express, which does not work with this config.  HMR works for me.  I've been trying to find out how to add SASS/SCSS support.  Anyone know?

**Comment by zsmorris** [comment]
Thanks for the quick reply!  Didn't work for me, unfortunately.

You've probably already seen this, but I've also been looking at how to incorporate SASS and this is the best I found:  [https://github.com/aurelia/webpack-plugin/issues/14](https://github.com/aurelia/webpack-plugin/issues/14)

**Comment by zsmorris** [comment]
It doesn't look like the webpack build process is being triggered at all when a project build is executed from Visual Studio (the files in wwwroot/dist do not change when a change is made to any client component file).

**Comment by zsmorris** [comment]
After some experimentation, I can get app.js to be rebuilt only if I add a script to package.json calling webpack:  ` "scripts":{ "build": "webpack"} ` and then invoking that script manually from command line:  `npm run build` .  Can't get VS to trigger webpack as part of VS build.  

(Not sure how far away from HMR problem we're getting here...)

**Comment by zsmorris** [comment]
So, I've got HMR to work.  Switching to "my-project" instead of "IIS Express" in the debug dropdown didn't work for me.  It defaults to IIS, HMR not working.  I switched to "my-project", HMR still not working. Switch _BACK_ to IIS, HMR now working.

For some reason, VS was returning `false` from this line in Startup.cs:  `env.IsDevelopment()` by default, which caused the ASP middleware for webpack to not be loaded:  
 ```
if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();

                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {HotModuleReplacement = true});
            }
```
After switching _BACK_ to IIS for debug, `env.IsDevelopment()` returns `true `and webpack middleware runs as expected.

Thanks VS! Good times!

**Comment by HamedFathi** [comment]
@zsmorris 

Nop, I dont confirm that, I change the code like below
```
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
			
                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
                    HotModuleReplacement = true
                });
				
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();


            }
```

now HotModuleReplacement should work in any conditions so I build the project and run it by dotnet run but HotModuleReplacement  does not work still

I think something is wrong

**Comment by apatton724** [comment]
**Got it semi-working**

I'm also  having problems, but it's now semi working for me. 

I had skipped this part of @EisenbergEffect, instructions:

> Before running the application, you will want to configure your environment so that the ASP.NET tooling runs in development mode. This enables auto-rebuild of the Aurelia client and Hot Module Reload. How you setup your environment variables depends on what platform and tools you are running.

> If you are using PowerShell on Windows, execute $Env:ASPNETCORE_ENVIRONMENT = "Development"
If you are using cmd.exe on Windows, execute setx ASPNETCORE_ENVIRONMENT "Development", and then restart your command prompt to make the change take effect.
If you’re using Mac/Linux, execute export ASPNETCORE_ENVIRONMENT=Development

So once, I set the in environment correctly, and ran "dotnet run", the command line correctly said I was running in "Development" mode.

**Problem**
I get HMR for any changes in the template file, but changes in the view-model are not automatically loading EVENTHOUGH, I do see in the browser-console that the view model was updated: 

`Running default HMR for app/components/home/home
process-update.js:100 [HMR] Updated modules:
process-update.js:102 [HMR]  - ./ClientApp/app/components/home/home.ts
process-update.js:107 [HMR] App is up to date.
aurelia-hot-module-reload.js:132 Analyzing app/components/home/home->Home
aurelia-hot-module-reload.js:155 Replacing function Home() {
        this.test_v = "home";
        this.currentCount = 0;
    } with function Home() {
        this.test_v = "bigger home";
        this.currentCount = 0;
    }`

@niieani, is webpack/hmr still in experimental stage?

Thank you guys. Really looking forward to swapping out jspm/gulp for webpack in production

**Comment by niieani** [comment]
@apatton724 unfortunately yes, HMR is still experimental. We don't have enough capacity on the team to work on HMR, since SSR is currently a higher priority and HMR is so complex to get right.

**Comment by EisenbergEffect** [comment]
@apatton724 Contributions are always welcome :) We'll turn our attention back to HMR, as a team, after we land a few other important items for the ecosystem (SSR, new/improved docs, forum, Webpack/Aurelia CLI integration). In the mean time, please dig in and see what you can discover :)

**Comment by HamedFathi** [comment]
@EisenbergEffect ,
wow wow Webpack/Aurelia CLI integration is so cool :D

Ok thanks Rob for your clarification, so I close it.

Long live the Aurelia

**Comment by apatton724** [comment]
I'll take you up on that offer @EisenbergEffect ; btw, ssr would be great!
